apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bertobert-bertobert-poi-gateway-app-dev
  annotations:
    argocd/app-name: bertobert-bertobert-poi-gateway-app-dev
    backstage.io/kubernetes-id: bertobert-bertobert-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: bertobert
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=bertobert-bertobert-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/bertobert-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/bertobert/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/bertobert/deployments/bertobert-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/bertobert-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/bertobert"
  system: workshop-system-bertobert
  providesApis:
    - gateway-api-bertobert
  consumesApis:
    - backend-api-bertobert
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-bertobert
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/bertobert"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-bertobert
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://bertobert-poi-gateway-app-bertobert.apps.summit23rock.n26o.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus1/bertobert-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/bertobert"
  system: workshop-system-bertobert
  definition:
    $text: https://github.com/Summit23Janus1/bertobert-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
